name: "Bug Report 🐛"
description: "Please report any issues or unexpected behavior in the app."
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: bug
    attributes:
      label: "🐞 What is the bug?"
      placeholder: "e.g., Clicking the 'Complete Quest' button does not increase XP."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "🔁 How to reproduce it"
      placeholder: "Please describe the situation where the bug occurred."