name: "Feature Spec 📦"
description: "Define the feature to be implemented and outline the plan before starting development."
title: "[feat] "
labels: [feat]
body:
  - type: textarea
    id: summary
    attributes:
      label: "📌 What is the feature?"
      placeholder: "e.g., New user profile UI and edit functionality"
    validations:
      required: true

  - type: textarea
    id: flow
    attributes:
      label: "🔁 Expected user flow (optional)"
      placeholder: "e.g., Dashboard > Click 'Edit Profile' > Modify fields > Save changes"
    validations:
      required: false

  - type: textarea
    id: data
    attributes:
      label: "🧩 Required data or state (optional)"
      placeholder: "e.g., User info object, editable fields, validation rules"
    validations:
      required: false

  - type: textarea
    id: checklist
    attributes:
      label: "✅ Tasks to implement (checklist)"
      placeholder: |
        - [ ] Build UI components
        - [ ] Connect to API
        - [ ] Add input validation
        - [ ] Handle error states
    validations:
      required: false
