name: "Refactor / Chore 🛠️"
description: "For non-feature tasks like code refactoring or config updates."
title: "[Chore] "
labels: [chore]
body:
  - type: textarea
    id: task
    attributes:
      label: "🧹 What is the task?"
      placeholder: "e.g., Restructure component folders, update ESLint settings."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "🔍 Reason or context for the task"
      placeholder: "e.g., To reorganize atomic structure, remove unnecessary dependencies, etc."
    validations:
      required: false

  - type: textarea
    id: checklist
    attributes:
      label: "✅ Task items"
      placeholder: |
        - [ ] Remove unnecessary folders
        - [ ] Update eslint settings
        - [ ] Reconfigure tsconfig paths
    validations:
      required: false
