name: "Refactor / Chore 🛠️"
description: "코드 정리, 설정 변경 등 기능 외 작업을 정리해주세요"
title: "[Chore] "
labels: [chore]
body:
  - type: textarea
    id: task
    attributes:
      label: "🧹 어떤 작업인가요?"
      placeholder: "예: 컴포넌트 폴더 구조 정리, ESLint 설정 업데이트 등"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "🔍 작업 이유 or 배경"
      placeholder: "예: Atomic 구조 재정비를 위해, 불필요한 의존성 제거 등"
    validations:
      required: false

  - type: textarea
    id: checklist
    attributes:
      label: "✅ 작업 항목"
      placeholder: |
        - [ ] 불필요한 폴더 제거
        - [ ] eslint 설정 업데이트
        - [ ] tsconfig 경로 재설정
    validations:
      required: false
