name: "Refactor / Chore 🛠️"
description: "Summarize non-feature tasks such as code cleanup, config updates, etc."
title: "[Chore] "
labels: [chore]
body:
  - type: textarea
    id: task
    attributes:
      label: "🧹 What kind of task is this?"
      placeholder: "e.g., Refactored component folder structure, updated ESLint config, etc."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "🔍 Reason or Background"
      placeholder: "e.g., To reorganize the atomic structure, removed unused dependencies, etc."
    validations:
      required: false

  - type: textarea
    id: checklist
    attributes:
      label: "✅ Task Items"
      placeholder: |
        - [ ] Removed unnecessary folders
        - [ ] Updated ESLint config
        - [ ] Reconfigured tsconfig paths
    validations:
      required: false
